window.TOURS_ICI_CATEGORIES = [
  { id: "all", label: "Tout", icon: "assets/icon-all.svg", color: "#0E2233", dark: "#0E2233" },
  { id: "restaurant", label: "Restaurants", icon: "assets/icon-restaurant.svg", color: "#F2765F", dark: "#9F3F35" },
  { id: "bar", label: "Bars", icon: "assets/icon-bar.svg", color: "#1BB6BD", dark: "#0D7075" },
  { id: "kebab", label: "Kebabs", icon: "assets/icon-kebab.svg", color: "#F39A3D", dark: "#975321" },
  { id: "pub", label: "Pubs", icon: "assets/icon-pub.svg", color: "#4D9D82", dark: "#416B58" },
  { id: "nightclub", label: "Discothèques", icon: "assets/icon-nightclub.svg", color: "#7E5E9B", dark: "#583663" },
  { id: "cafe", label: "Cafés", icon: "assets/icon-cafe.svg", color: "#B37A62", dark: "#754732" },
  { id: "culture", label: "Culture", icon: "assets/icon-culture.svg", color: "#3F78A8", dark: "#285171" }
];

/*
  Les fiches ci-dessous sont volontairement des EXEMPLES DE DÉMONSTRATION.
  Remplacez-les depuis admin.html par des lieux réellement rencontrés et vérifiés.
*/
window.TOURS_ICI_DEMO_PLACES = [
  {
    id: "demo-restaurant",
    name: "Table tourangelle — Démo",
    category: "restaurant",
    address: "Centre-ville de Tours",
    district: "Centre",
    lat: 47.3944,
    lng: 0.6848,
    description: "Fiche de démonstration pour visualiser un restaurant local. À remplacer par une adresse réellement rencontrée.",
    tags: ["Cuisine locale", "Convivial", "Terrasse"],
    price: "€€",
    phone: "",
    website: "",
    verified: false,
    hours: { open: "12:00", close: "22:30" },
    colors: ["#EF6F61", "#F5B642"]
  },
  {
    id: "demo-bar",
    name: "Bar du quartier — Démo",
    category: "bar",
    address: "Vieux-Tours",
    district: "Vieux-Tours",
    lat: 47.3949,
    lng: 0.6815,
    description: "Exemple de fiche bar avec ambiance, horaires, itinéraire, partage et favoris.",
    tags: ["Cocktails", "Afterwork", "Musique"],
    price: "€€",
    phone: "",
    website: "",
    verified: false,
    hours: { open: "17:00", close: "01:30" },
    colors: ["#159D99", "#3F75A2"]
  },
  {
    id: "demo-kebab",
    name: "Kebab généreux — Démo",
    category: "kebab",
    address: "Secteur Jean-Jaurès",
    district: "Jean-Jaurès",
    lat: 47.3899,
    lng: 0.6925,
    description: "Exemple de fiche restauration rapide avec informations simples et immédiatement lisibles.",
    tags: ["Petit budget", "Sur place", "À emporter"],
    price: "€",
    phone: "",
    website: "",
    verified: false,
    hours: { open: "11:30", close: "23:30" },
    colors: ["#E58B45", "#EF6F61"]
  },
  {
    id: "demo-pub",
    name: "Pub chaleureux — Démo",
    category: "pub",
    address: "Quartier Plumereau",
    district: "Plumereau",
    lat: 47.3948,
    lng: 0.6823,
    description: "Exemple de pub à personnaliser avec vos propres photos et votre rencontre avec le responsable.",
    tags: ["Bières", "Matchs", "Entre amis"],
    price: "€€",
    phone: "",
    website: "",
    verified: false,
    hours: { open: "16:00", close: "02:00" },
    colors: ["#6F9D88", "#159D99"]
  },
  {
    id: "demo-nightclub",
    name: "Club de nuit — Démo",
    category: "nightclub",
    address: "Tours",
    district: "Centre",
    lat: 47.3920,
    lng: 0.6875,
    description: "Exemple de fiche sortie nocturne avec catégorie très visible et partage rapide.",
    tags: ["Danse", "DJ", "Ouvert tard"],
    price: "€€€",
    phone: "",
    website: "",
    verified: false,
    hours: { open: "23:00", close: "05:00" },
    colors: ["#865D91", "#3F75A2"]
  },
  {
    id: "demo-cafe",
    name: "Café calme — Démo",
    category: "cafe",
    address: "Tours centre",
    district: "Centre",
    lat: 47.3907,
    lng: 0.6894,
    description: "Exemple de café pour travailler, discuter ou prendre un goûter.",
    tags: ["Calme", "Goûter", "Wi-Fi"],
    price: "€",
    phone: "",
    website: "",
    verified: false,
    hours: { open: "08:00", close: "19:00" },
    colors: ["#B77A5C", "#F5B642"]
  },
  {
    id: "demo-culture",
    name: "Lieu culturel — Démo",
    category: "culture",
    address: "Tours",
    district: "Centre",
    lat: 47.3958,
    lng: 0.6942,
    description: "Exemple de musée ou lieu culturel. Vérifiez les règles de photographie avant toute publication.",
    tags: ["Musée", "Famille", "Patrimoine"],
    price: "€",
    phone: "",
    website: "",
    verified: false,
    hours: { open: "10:00", close: "18:00" },
    colors: ["#3F75A2", "#159D99"]
  }
];
